# Generated by Django 4.0.6 on 2022-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
